# include common source and gems
source "https://rubygems.org" do
  gem 'rack'
  gem 'sinatra', '~>1.4'
  gem 'sinatra-contrib'
end


# include codekit source and gem
gem 'att-codekit', '~>6.0',
  :require => 'att/codekit',
  :source => "https://lprod.code-api-att.com/gemserver/"
