/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 */

/*
 * ====================================================================
 * LICENSE: Licensed by AT&T under the 'Software Development Kit Tools
 * Agreement.' 2013.
 * TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTIONS:
 * http://developer.att.com/sdk_agreement/
 *
 * Copyright 2013 AT&T Intellectual Property. All rights reserved.
 * For more information contact developer.support@att.com
 * ====================================================================
 */

package com.att.api.rest;

/**
 * Holds any errors generated by the <code>RESTClient</code>.
 *
 * @author pk9069
 * @version 1.0
 * @since 1.0
 */
public class RESTException extends Exception {
    /** Serial version UDI. */
    private static final long serialVersionUID = -6874042744590915838L;

    /** Http status code. */
    private final int statusCode;

    /** Error message. */
    private final String errorMessage;

    /**
     * Creates a RESTException with the specified error message.
     *
     * @param errorMessage error message
     */
    public RESTException(final String errorMessage) {
        this(-1, errorMessage);
    }

    /**
     * Creates a RESTException that Wraps a <code>Throwable</code> object.
     *
     * @param cause <code>Throwable</code> object to wrap
     */
    public RESTException(final Throwable cause) {
        super(cause);
        this.statusCode = -1;
        this.errorMessage = cause.getMessage();
    }

    /**
     * Creates a RESTException object with the specified status code and error
     * message.
     *
     * @param statusCode http status code
     * @param errorMessage error message
     */
    public RESTException(final int statusCode, final String errorMessage) {
        super(errorMessage);
        this.statusCode = statusCode;
        this.errorMessage = errorMessage;
    }

    /**
     * Gets http status code or -1 if there wasn't any.
     *
     * @return status code
     */
    public int getStatusCode() {
        return this.statusCode;
    }

    /**
     * Gets error message.
     *
     * @return error message
     */
    public String getErrorMessage() {
        return this.errorMessage;
    }
}
