# include common source and gems
source "https://rubygems.org"

gem 'sinatra', '~>1.4'
gem 'sinatra-contrib'
gem 'immutable_struct', '~>1.1'
gem 'json', '~>1.8'
gem 'thin', '~>1.6'
gem 'mime-types', '~>1.0'
gem 'rack', '~>1.5'
gem 'rest-client', '~>1.6'


# include codekit source and gem
source "http://ldev.code-api-att.com:8808"
gem 'att-codekit', '~>3.0', :require => 'att/codekit'
